//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C0DEC0RE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C0DEC0RE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Library Data Access Application Block.
        /// </summary>
        internal static string BlockName {
            get {
                return ResourceManager.GetString("BlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object builder has no strategies..
        /// </summary>
        internal static string BuilderHasNoStrategies {
            get {
                return ResourceManager.GetString("BuilderHasNoStrategies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1} / {2} :: {3}.
        /// </summary>
        internal static string BuilderStrategyTraceBuildUp {
            get {
                return ResourceManager.GetString("BuilderStrategyTraceBuildUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1} :: {2}.
        /// </summary>
        internal static string BuilderStrategyTraceTearDown {
            get {
                return ResourceManager.GetString("BuilderStrategyTraceTearDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BuilderBase] Finished BuildUp on {0} with ID {1}.
        /// </summary>
        internal static string BuildUpFinished {
            get {
                return ResourceManager.GetString("BuildUpFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BuilderBase] Starting BuildUp on {0} with ID {1}.
        /// </summary>
        internal static string BuildUpStarting {
            get {
                return ResourceManager.GetString("BuildUpStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling constructor({0}).
        /// </summary>
        internal static string CallingConstructor {
            get {
                return ResourceManager.GetString("CallingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling method {0}({1}).
        /// </summary>
        internal static string CallingMethod {
            get {
                return ResourceManager.GetString("CallingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling IBuilderAware.OnBuiltUp().
        /// </summary>
        internal static string CallingOnBuiltUp {
            get {
                return ResourceManager.GetString("CallingOnBuiltUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling IBuilderAware.OnTearingDown().
        /// </summary>
        internal static string CallingOnTearingDown {
            get {
                return ResourceManager.GetString("CallingOnTearingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting property {0}({1}).
        /// </summary>
        internal static string CallingProperty {
            get {
                return ResourceManager.GetString("CallingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create an instance of type &apos;{0}&apos;..
        /// </summary>
        internal static string CannotCreateInstanceOfType {
            get {
                return ResourceManager.GetString("CannotCreateInstanceOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In class &apos;{0}&apos;, cannot inject value on property &apos;{1}&apos; because it is read-only..
        /// </summary>
        internal static string CannotInjectReadOnlyProperty {
            get {
                return ResourceManager.GetString("CannotInjectReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands Executed/sec is the rate at which database commands were executed..
        /// </summary>
        internal static string CommandExecutedCounterHelpResource {
            get {
                return ResourceManager.GetString("CommandExecutedCounterHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands Failed/sec is tha rate at which database commands failed to execute..
        /// </summary>
        internal static string CommandFailedCounterHelpResource {
            get {
                return ResourceManager.GetString("CommandFailedCounterHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuration failure occurred while creating database ‘{0}’..
        /// </summary>
        internal static string ConfigurationFailureCreatingDatabase {
            get {
                return ResourceManager.GetString("ConfigurationFailureCreatingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections Failed/sec is the rate at which database connections failed to open..
        /// </summary>
        internal static string ConnectionFailedCounterHelpResource {
            get {
                return ResourceManager.GetString("ConnectionFailedCounterHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections Opened/sec is the rate at which database connections were opened..
        /// </summary>
        internal static string ConnectionOpenedCounterHelpResource {
            get {
                return ResourceManager.GetString("ConnectionOpenedCounterHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Library Data Performance Counter Instances.
        /// </summary>
        internal static string CounterCategoryHelpResourceName {
            get {
                return ResourceManager.GetString("CounterCategoryHelpResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate dependency &quot;{0}&quot;..
        /// </summary>
        internal static string DependencyMissing {
            get {
                return ResourceManager.GetString("DependencyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string used was &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorConnectionFailedExtraInformation {
            get {
                return ResourceManager.GetString("ErrorConnectionFailedExtraInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error occurred using the &quot;{0}&quot; database instance while attempting to open the database connection..
        /// </summary>
        internal static string ErrorConnectionFailedMessage {
            get {
                return ResourceManager.GetString("ErrorConnectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception that occured was: {0}.
        /// </summary>
        internal static string EventLogEntryExceptionTemplate {
            get {
                return ResourceManager.GetString("EventLogEntryExceptionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in application {0} in the {1}..
        /// </summary>
        internal static string EventLogEntryHeaderTemplate {
            get {
                return ResourceManager.GetString("EventLogEntryHeaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not derive from IDictionary..
        /// </summary>
        internal static string ExceptionArgumentShouldDeriveFromIDictionary {
            get {
                return ResourceManager.GetString("ExceptionArgumentShouldDeriveFromIDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not derive from IList..
        /// </summary>
        internal static string ExceptionArgumentShouldDeriveFromIList {
            get {
                return ResourceManager.GetString("ExceptionArgumentShouldDeriveFromIList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [Assembler] attribute is not set in the configuration object type {0}..
        /// </summary>
        internal static string ExceptionAssemblerAttributeNotSet {
            get {
                return ResourceManager.GetString("ExceptionAssemblerAttributeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembler configured for type {0} has type {2} which is not compatible with type {1}..
        /// </summary>
        internal static string ExceptionAssemblerTypeNotCompatible {
            get {
                return ResourceManager.GetString("ExceptionAssemblerTypeNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base ConfigurationSourceElement configuration type can not be used as a concrete configuration element..
        /// </summary>
        internal static string ExceptionBaseConfigurationSourceElementIsInvalid {
            get {
                return ResourceManager.GetString("ExceptionBaseConfigurationSourceElementIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AssemblyQualifiedTypeNameConverter can only convert values of type &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionCanNotConvertType {
            get {
                return ResourceManager.GetString("ExceptionCanNotConvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command must be a SqlCommand..
        /// </summary>
        internal static string ExceptionCommandNotSqlCommand {
            get {
                return ResourceManager.GetString("ExceptionCommandNotSqlCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section {0} could not be saved because the file does not exist..
        /// </summary>
        internal static string ExceptionConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("ExceptionConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file {0} could not be found..
        /// </summary>
        internal static string ExceptionConfigurationLoadFileNotFound {
            get {
                return ResourceManager.GetString("ExceptionConfigurationLoadFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration object for type &apos;{0}&apos; with name &apos;{1}&apos; has type &apos;{2}&apos; which is does not implement ICustomProviderData..
        /// </summary>
        internal static string ExceptionConfigurationObjectIsNotCustomProviderData {
            get {
                return ResourceManager.GetString("ExceptionConfigurationObjectIsNotCustomProviderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The concrete type for polymorphic object named &apos;{1}&apos; in hierarchy {2} is not defined in configuration object {0}..
        /// </summary>
        internal static string ExceptionConfigurationObjectWithTypeDoesNotHaveTypeSet {
            get {
                return ResourceManager.GetString("ExceptionConfigurationObjectWithTypeDoesNotHaveTypeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration source section is not found in the application configuration file..
        /// </summary>
        internal static string ExceptionConfigurationSourceSectionNotFound {
            get {
                return ResourceManager.GetString("ExceptionConfigurationSourceSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [CustomFactory] attribute was not found on type {0} while processing request for id &apos;{1}&apos;..
        /// </summary>
        internal static string ExceptionCustomFactoryAttributeNotFound {
            get {
                return ResourceManager.GetString("ExceptionCustomFactoryAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database type {0} for the name {1} does not have the required [DatabaseAssembler] attribute required to build the database object..
        /// </summary>
        internal static string ExceptionDatabaseTypeDoesNotHaveAssemblerAttribute {
            get {
                return ResourceManager.GetString("ExceptionDatabaseTypeDoesNotHaveAssemblerAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database type {0} does not have the required ConfigurationElementType attribute..
        /// </summary>
        internal static string ExceptionDatabaseTypeDoesNotHaveRequiredConfigurationTypeAttribute {
            get {
                return ResourceManager.GetString("ExceptionDatabaseTypeDoesNotHaveRequiredConfigurationTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error raising an event in .
        /// </summary>
        internal static string ExceptionEventRaisingFailed {
            get {
                return ResourceManager.GetString("ExceptionEventRaisingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method with signature {0} is not a valid factory method to build type {1}..
        /// </summary>
        internal static string ExceptionFactoryMethodHasInvalidReturnType {
            get {
                return ResourceManager.GetString("ExceptionFactoryMethodHasInvalidReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; cannot be resolved. Please verify the spelling is correct or that the full type name is provided..
        /// </summary>
        internal static string ExceptionInvalidType {
            get {
                return ResourceManager.GetString("ExceptionInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of parameters does not match number of values for stored procedure..
        /// </summary>
        internal static string ExceptionMessageParameterMatchFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageParameterMatchFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one command must be initialized.
        /// </summary>
        internal static string ExceptionMessageUpdateDataSetArgumentFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageUpdateDataSetArgumentFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update row .
        /// </summary>
        internal static string ExceptionMessageUpdateDataSetRowFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageUpdateDataSetRowFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration could not be found for name &apos;{0}&apos; in factory {1}..
        /// </summary>
        internal static string ExceptionNamedConfigurationNotFound {
            get {
                return ResourceManager.GetString("ExceptionNamedConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not contain the ConfigurationElementTypeAttribute..
        /// </summary>
        internal static string ExceptionNoConfigurationElementAttribute {
            get {
                return ResourceManager.GetString("ExceptionNoConfigurationElementAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested database {0} is not defined in configuration..
        /// </summary>
        internal static string ExceptionNoDatabaseDefined {
            get {
                return ResourceManager.GetString("ExceptionNoDatabaseDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not have a public method annotated as an injection target as required by the use of injection..
        /// </summary>
        internal static string ExceptionNoMethodAnnotatedForInjectionFound {
            get {
                return ResourceManager.GetString("ExceptionNoMethodAnnotatedForInjectionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested database {0} does not have provider name set in the connection string..
        /// </summary>
        internal static string ExceptionNoProviderDefinedForConnectionString {
            get {
                return ResourceManager.GetString("ExceptionNoProviderDefinedForConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not have a static method with a TargetConstructorAttribuite suitable to create an object of type {1}..
        /// </summary>
        internal static string ExceptionNoSuitableFactoryMethodFound {
            get {
                return ResourceManager.GetString("ExceptionNoSuitableFactoryMethodFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type attribute does not exist on the element {0}..
        /// </summary>
        internal static string ExceptionNoTypeAttribute {
            get {
                return ResourceManager.GetString("ExceptionNoTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value can not be null or an empty string..
        /// </summary>
        internal static string ExceptionNullOrEmptyString {
            get {
                return ResourceManager.GetString("ExceptionNullOrEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter discovery is not supported for connections using GenericDatabase. You must specify the parameters explicitly, or configure the connection to use a type deriving from Database that supports parameter discovery..
        /// </summary>
        internal static string ExceptionParameterDiscoveryNotSupportedOnGenericDatabase {
            get {
                return ResourceManager.GetString("ExceptionParameterDiscoveryNotSupportedOnGenericDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; for injection target &apos;{1}&apos; in type &apos;{2}&apos; is missing the injection interpretation attribute..
        /// </summary>
        internal static string ExceptionParameterNotAnnotatedForInjection {
            get {
                return ResourceManager.GetString("ExceptionParameterNotAnnotatedForInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The performance counter &apos;{0}&apos; in category &apos;{1}&apos; is redefined in type {2} with a different configuration..
        /// </summary>
        internal static string ExceptionPerformanceCounterRedefined {
            get {
                return ResourceManager.GetString("ExceptionPerformanceCounterRedefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e {2}..
        /// </summary>
        internal static string ExceptionPropertyNotFound {
            get {
                return ResourceManager.GetString("ExceptionPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not contain the ConfigurationDataRetrievalAttribute required to resolve named references..
        /// </summary>
        internal static string ExceptionRetrievalAttributeNotFound {
            get {
                return ResourceManager.GetString("ExceptionRetrievalAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve parameter value. The property {0} does not exist for type {1}..
        /// </summary>
        internal static string ExceptionSourcePropertyDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionSourcePropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value can not be null or string or empty..
        /// </summary>
        internal static string ExceptionStringNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionStringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system configuration source is not defined in the configuration file..
        /// </summary>
        internal static string ExceptionSystemSourceNotDefined {
            get {
                return ResourceManager.GetString("ExceptionSystemSourceNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table name array used to map results to user-specified table names cannot be empty..
        /// </summary>
        internal static string ExceptionTableNameArrayEmpty {
            get {
                return ResourceManager.GetString("ExceptionTableNameArrayEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} from configuration could not be created..
        /// </summary>
        internal static string ExceptionTypeCouldNotBeCreated {
            get {
                return ResourceManager.GetString("ExceptionTypeCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not an implementation of ICustomFactory for CustomFactoryAttribute..
        /// </summary>
        internal static string ExceptionTypeNotCustomFactory {
            get {
                return ResourceManager.GetString("ExceptionTypeNotCustomFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not an implementation of IDatabaseAssembler for DatabaseAssemblerAttribute..
        /// </summary>
        internal static string ExceptionTypeNotDatabaseAssembler {
            get {
                return ResourceManager.GetString("ExceptionTypeNotDatabaseAssembler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not an implementation of IConfigurationNameMapper for ConfigurationNameMapperAttribute..
        /// </summary>
        internal static string ExceptionTypeNotNameMapper {
            get {
                return ResourceManager.GetString("ExceptionTypeNotNameMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not an implementation of IConfigurationDataRetriever for ConfigurationDataRetrievalAttribute..
        /// </summary>
        internal static string ExceptionTypeNotRetriever {
            get {
                return ResourceManager.GetString("ExceptionTypeNotRetriever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected type &apos;{0}&apos; was not provided..
        /// </summary>
        internal static string ExceptionUnexpectedType {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Configuration Source.
        /// </summary>
        internal static string FileConfigurationSourceName {
            get {
                return ResourceManager.GetString("FileConfigurationSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many dependency injection attributes defined on {0}.{1}..
        /// </summary>
        internal static string InvalidAttributeCombination {
            get {
                return ResourceManager.GetString("InvalidAttributeCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid enumeration value..
        /// </summary>
        internal static string InvalidEnumerationValue {
            get {
                return ResourceManager.GetString("InvalidEnumerationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with the given key is already present in the dictionary..
        /// </summary>
        internal static string KeyAlreadyPresentInDictionary {
            get {
                return ResourceManager.GetString("KeyAlreadyPresentInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing policy to build {0} named &apos;{1}&apos;..
        /// </summary>
        internal static string MissingPolicyNamed {
            get {
                return ResourceManager.GetString("MissingPolicyNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing policy to build unnamed {0}..
        /// </summary>
        internal static string MissingPolicyUnnamed {
            get {
                return ResourceManager.GetString("MissingPolicyUnnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an appropriately matching constructor..
        /// </summary>
        internal static string NoAppropriateConstructor {
            get {
                return ResourceManager.GetString("NoAppropriateConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password,pwd.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered as singleton.
        /// </summary>
        internal static string SingletonRegistered {
            get {
                return ResourceManager.GetString("SingletonRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning existing singleton.
        /// </summary>
        internal static string SingletonReturned {
            get {
                return ResourceManager.GetString("SingletonReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration Source.
        /// </summary>
        internal static string SystemConfigurationSourceName {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BuilderBase] Finished TearDown on {0}.
        /// </summary>
        internal static string TearDownFinished {
            get {
                return ResourceManager.GetString("TearDownFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BuilderBase] Starting TearDown on {0}.
        /// </summary>
        internal static string TearDownStarting {
            get {
                return ResourceManager.GetString("TearDownStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped to {0} / {1}.
        /// </summary>
        internal static string TypeMapped {
            get {
                return ResourceManager.GetString("TypeMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While resolving dependencies for {2}, the provided type {1} is not compatible with {0}..
        /// </summary>
        internal static string TypeNotCompatible {
            get {
                return ResourceManager.GetString("TypeNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id,uid.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
